default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('BD_SERVIDOR', '/var/www/var/run/postgresql') %>
  username: <%= ENV.fetch('BD_USUARIO', 'sipdes') %>
  password: <%= ENV.fetch('BD_CLAVE') %>

development:
  <<: *default
  database: <%= ENV.fetch('BD_DES', 'sal7711cinep_des') %>

test:
  <<: *default
  database: <%= ENV.fetch('BD_PRUEBA', 'sal7711cinep_pru') %>

ensayo:
  <<: *default
  database: <%= ENV.fetch('BD_ENSAYO', 'sal7711cinep_ensayo') %>

production:
  <<: *default
  database: <%= ENV.fetch('BD_PRO', 'sal7711cinep_pro') %>

